setwd("~/Desktop/exploratory data/Assignment_1/")
db <- read.table("household_power_consumption.txt",header=T, sep = ";",na.strings = "?")
db$Date <- as.Date(db$Date,format="%d/%m/%Y")
db1 <- subset(db, Date >= "2007-02-01" & Date <= "2007-02-02")
db1$DateTime <- paste(db1$Date, db1$Time)
db1$DateTime <- strptime(db1$DateTime,"%Y-%m-%d %H:%M:%S")
png(file = "plot4.png", width = 480, height =480)
par(mfrow = c(2,2))
plot(db1$DateTime, db1$Global_active_power, type = "l", main = "", xlab = "", ylab="Global Active Power (kilowatts)")
plot(db1$DateTime, db1$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(db1$DateTime, db1$Sub_metering_1, type = "l", main = "", xlab = "", ylab="Energy sub metering")
points(db1$DateTime, db1$Sub_metering_2, type = "l", col = "blue")
points(db1$DateTime, db1$Sub_metering_3, type = "l", col = "red")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1), col = c(1,"red","blue"), bty = "n")
plot(db1$DateTime, db1$Global_reactive_power, type = "l", main = "", xlab = "", ylab="Global_reactive_power")
dev.off()
