setwd("~/Desktop/exploratory data/Assignment_1/")
db <- read.table("household_power_consumption.txt",header=T, sep = ";",na.strings = "?")
db$Date <- as.Date(db$Date,format="%d/%m/%Y")
db1 <- subset(db, Date >= "2007-02-01" & Date <= "2007-02-02")
db1$DateTime <- paste(db1$Date, db1$Time)
db1$DateTime <- strptime(db1$DateTime,"%Y-%m-%d %H:%M:%S")
png(file = "plot2.png", width = 480, height =480)
plot(db1$DateTime, db1$Global_active_power, type = "l", main = "", xlab = "", ylab="Global Active Power (kilowatts)")
dev.off()