setwd("~/Desktop/exploratory data/Assignment_1/")
db <- read.table("household_power_consumption.txt",header=T, sep = ";",na.strings = "?")
db$Date <- as.Date(db$Date,format="%d/%m/%Y")
db1 <- subset(db, Date >= "2007-02-01" & Date <= "2007-02-02")
db1$DateTime <- paste(db1$Date, db1$Time)
db1$DateTime <- strptime(db1$DateTime,"%Y-%m-%d %H:%M:%S")
png(file = "plot1.png", width = 480, height =480)
hist(db1[,3],col=2,main = "Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()